# Generated by Django 2.2.1 on 2019-10-21 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Book_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(max_length=35)),
                ('Book_Price', models.IntegerField(default=True)),
                ('Publisher', models.CharField(max_length=25)),
                ('Edition', models.CharField(max_length=25, null=True)),
                ('Descrition', models.CharField(max_length=100, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('of_shop', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('couse_name', models.CharField(max_length=25, unique=True)),
                ('school', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=35)),
                ('product_price', models.IntegerField(default=250)),
                ('product_brand', models.CharField(max_length=25)),
                ('product_models', models.CharField(max_length=25)),
                ('description_text', models.CharField(default='These is for sell', max_length=100)),
                ('garantee', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('of_shop', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=20)),
                ('city', models.CharField(default='Vellore', max_length=15)),
                ('Building_no', models.CharField(max_length=15, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=10)),
                ('m_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
                ('Hostel_Type', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('Block', models.CharField(default='G', max_length=1)),
                ('Email_Id', models.EmailField(max_length=254, unique=True)),
                ('DOB', models.DateField(default='2000-01-01', null=True)),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managers_name', models.CharField(max_length=35)),
                ('manager_mobile', models.IntegerField()),
                ('manager_email', models.URLField(unique=True)),
                ('manager_address', models.CharField(max_length=25)),
                ('stores_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.Stores')),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=35)),
                ('item_price', models.IntegerField()),
                ('descrition_text', models.CharField(default='These is for sell', max_length=100)),
                ('sold', models.BooleanField(default=False)),
                ('of_shop', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Stores')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Basket',
            fields=[
                ('basket_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('books', models.ManyToManyField(to='first_app.Books')),
                ('electories_items', models.ManyToManyField(to='first_app.Electronics')),
                ('sports_items', models.ManyToManyField(to='first_app.Sports')),
            ],
        ),
        migrations.AddField(
            model_name='electronics',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Stores'),
        ),
        migrations.AddField(
            model_name='electronics',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='Course_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.Courses'),
        ),
        migrations.AddField(
            model_name='books',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Stores'),
        ),
        migrations.AddField(
            model_name='books',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
