# Generated by Django 2.2.1 on 2019-10-21 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20191021_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Course_Id',
            field=models.ForeignKey(default="I don't know course code", null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.Courses'),
        ),
        migrations.AlterField(
            model_name='books',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
