# Generated by Django 2.2.1 on 2019-10-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20191021_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Course_Id',
            field=models.ForeignKey(default='No Course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.Courses'),
        ),
    ]
