# Generated by Django 2.2.1 on 2019-10-22 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0006_auto_20191021_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_basket',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='shopping_basket',
            name='books',
        ),
        migrations.AddField(
            model_name='shopping_basket',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.Books'),
        ),
        migrations.RemoveField(
            model_name='shopping_basket',
            name='electories_items',
        ),
        migrations.AddField(
            model_name='shopping_basket',
            name='electories_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.Electronics'),
        ),
        migrations.RemoveField(
            model_name='shopping_basket',
            name='sports_items',
        ),
        migrations.AddField(
            model_name='shopping_basket',
            name='sports_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.Sports'),
        ),
    ]
