# Generated by Django 2.2.1 on 2019-10-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20191022_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_basket',
            name='time_of_purchase',
            field=models.TimeField(auto_now=True),
        ),
    ]
