# Generated by Django 2.2.1 on 2019-10-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_shopping_basket_time_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='store_id',
            field=models.ForeignKey(default='No store', null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.Stores'),
        ),
    ]
