# Generated by Django 2.2.1 on 2019-10-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20191022_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='of_shop',
        ),
        migrations.RemoveField(
            model_name='books',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='of_shop',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='of_shop',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='store_id',
        ),
        migrations.AlterField(
            model_name='electronics',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
